---
# tasks file for node

# Install Dependencies
- name: Ensure node dependencies are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ node_dependencies | list }}"

- name: Define node_user
  set_fact:
    node_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  when: node_user is not defined

# Node Installation
- include_tasks: ppa.yml
  when: node_install_type == 'ppa'

- include_tasks: nvm.yml
  when: node_install_type == 'nvm'
